lab21.o: lab21.cpp lab21.h
   g++ -Wall -g -c lab21.cpp     

MyClass.o: MyClass.cpp MyClass.h
   g++ -Wall -g -c MyClass.cpp

output:  lab21.o MyClass.o  
   g++ -Wall -g -o lab21exe lab21.o MyClass.o

clean:
	rm *.o 